import { useState } from 'react'
import { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'
import toast from 'react-hot-toast'

export default function ExportMenu({ topic, style, explanation, followup, difficulty }) {
  const [open, setOpen] = useState(false)
  const [exporting, setExporting] = useState(null)

  const timestamp = new Date().toISOString().split('T')[0]
  const filename = `${topic?.replace(/[^a-z0-9]/gi, '_')}_${timestamp}`

  const exportMarkdown = () => {
    setExporting('md')
    try {
      const md = `# ${topic}

**Style:** ${style}
**Difficulty:** ${difficulty}/5
**Generated:** ${new Date().toLocaleDateString()}

---

${explanation}

---

## Check Your Understanding

${followup || 'N/A'}

---

*Generated by ELIM - Explain Like I'm Me*
`
      const blob = new Blob([md], { type: 'text/markdown' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${filename}.md`
      a.click()
      URL.revokeObjectURL(url)
      toast.success('MARKDOWN EXPORTED')
    } catch (e) {
      toast.error('EXPORT FAILED')
    }
    setExporting(null)
    setOpen(false)
  }

  const exportPDF = async () => {
    setExporting('pdf')
    try {
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      })

      const pageWidth = pdf.internal.pageSize.getWidth()
      const margin = 15
      const contentWidth = pageWidth - margin * 2
      let y = margin

      // Header
      pdf.setFillColor(10, 15, 30)
      pdf.rect(0, 0, pageWidth, 35, 'F')

      pdf.setTextColor(0, 229, 255)
      pdf.setFontSize(18)
      pdf.setFont('helvetica', 'bold')
      pdf.text('ELIM', margin, y + 8)

      pdf.setFontSize(9)
      pdf.setTextColor(100, 120, 140)
      pdf.text('EXPLAIN LIKE I\'M ME', margin, y + 14)

      y = 45

      // Topic
      pdf.setTextColor(230, 240, 255)
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      pdf.text(topic?.toUpperCase() || 'TOPIC', margin, y)
      y += 10

      // Meta
      pdf.setFontSize(9)
      pdf.setTextColor(100, 140, 160)
      pdf.setFont('helvetica', 'normal')
      pdf.text(`Style: ${style?.toUpperCase()}  |  Difficulty: ${difficulty}/5  |  ${new Date().toLocaleDateString()}`, margin, y)
      y += 12

      // Divider
      pdf.setDrawColor(0, 229, 255)
      pdf.setLineWidth(0.3)
      pdf.line(margin, y, pageWidth - margin, y)
      y += 10

      // Explanation
      pdf.setTextColor(50, 60, 70)
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'normal')

      const lines = pdf.splitTextToSize(explanation || '', contentWidth)
      const lineHeight = 5.5
      const pageHeight = pdf.internal.pageSize.getHeight()

      for (const line of lines) {
        if (y + lineHeight > pageHeight - 30) {
          pdf.addPage()
          y = margin
        }
        pdf.text(line, margin, y)
        y += lineHeight
      }

      // Followup section
      if (followup) {
        y += 8
        if (y > pageHeight - 50) {
          pdf.addPage()
          y = margin
        }

        pdf.setFillColor(245, 248, 255)
        pdf.roundedRect(margin, y - 4, contentWidth, 30, 2, 2, 'F')

        pdf.setTextColor(100, 80, 180)
        pdf.setFontSize(8)
        pdf.setFont('helvetica', 'bold')
        pdf.text('CHECK YOUR UNDERSTANDING', margin + 4, y + 2)

        pdf.setTextColor(60, 70, 90)
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'normal')
        const followupLines = pdf.splitTextToSize(followup, contentWidth - 8)
        y += 8
        for (const line of followupLines.slice(0, 3)) {
          pdf.text(line, margin + 4, y)
          y += 5
        }
      }

      // Footer
      const totalPages = pdf.internal.getNumberOfPages()
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i)
        pdf.setFontSize(8)
        pdf.setTextColor(150, 160, 170)
        pdf.text(
          `Generated by ELIM  |  Page ${i} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        )
      }

      pdf.save(`${filename}.pdf`)
      toast.success('PDF EXPORTED')
    } catch (e) {
      console.error(e)
      toast.error('PDF EXPORT FAILED')
    }
    setExporting(null)
    setOpen(false)
  }

  return (
    <div style={{ position: 'relative' }}>
      <button
        type="button"
        onClick={() => setOpen(!open)}
        style={{
          display: 'flex', alignItems: 'center', gap: 5,
          fontFamily: "'Share Tech Mono',monospace",
          fontSize: 9, letterSpacing: '0.12em',
          padding: '4px 10px', borderRadius: 2,
          border: '1px solid rgba(0,229,255,0.12)',
          background: open ? 'rgba(0,229,255,0.08)' : 'transparent',
          color: open ? 'var(--cyan)' : 'var(--sub)',
          cursor: 'pointer', transition: 'all 0.2s',
        }}
      >
        <svg width="11" height="11" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
            d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        EXPORT
      </button>

      {open && (
        <div style={{
          position: 'absolute',
          top: '100%',
          left: 0,
          marginTop: 4,
          background: 'var(--bg)',
          border: '1px solid rgba(0,229,255,0.2)',
          borderRadius: 3,
          overflow: 'hidden',
          zIndex: 100,
          minWidth: 120,
        }}>
          <button
            onClick={exportPDF}
            disabled={exporting}
            style={{
              display: 'flex', alignItems: 'center', gap: 8,
              width: '100%',
              padding: '0.6rem 0.875rem',
              fontFamily: "'Share Tech Mono',monospace",
              fontSize: 10, letterSpacing: '0.1em',
              color: 'var(--text)',
              background: 'transparent',
              border: 'none',
              borderBottom: '1px solid rgba(0,229,255,0.08)',
              cursor: exporting ? 'wait' : 'pointer',
              textAlign: 'left',
            }}
          >
            <svg width="12" height="12" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
            </svg>
            {exporting === 'pdf' ? 'EXPORTING...' : 'PDF'}
          </button>
          <button
            onClick={exportMarkdown}
            disabled={exporting}
            style={{
              display: 'flex', alignItems: 'center', gap: 8,
              width: '100%',
              padding: '0.6rem 0.875rem',
              fontFamily: "'Share Tech Mono',monospace",
              fontSize: 10, letterSpacing: '0.1em',
              color: 'var(--text)',
              background: 'transparent',
              border: 'none',
              cursor: exporting ? 'wait' : 'pointer',
              textAlign: 'left',
            }}
          >
            <svg width="12" height="12" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            {exporting === 'md' ? 'EXPORTING...' : 'MARKDOWN'}
          </button>
        </div>
      )}
    </div>
  )
}
